# See https://zellwk.com/blog/github-actions-deploy/ an explanation of this code
name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
           install -m 600 -D /dev/null ~/.ssh/id_rsa
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           host='us.sys2nix.de'
           hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
           ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
           ssh admin@us.sys2nix.de sudo rm -rf /var/www/html/nightgod.agency
           ssh admin@us.sys2nix.de sudo git clone https://github.com/mrtuxa/nightgod.agency.git /tmp/nightgod.agency
           ssh admin@us.sys2nix.de sudo mv /tmp/nightgod.agency /var/www/html/nightgod.agency
           ssh admin@us.sys2nix.de sudo rm -rf /tmp/nightgod.agency
           ssh admin@us.sys2nix.de "curl https://github.com/mrtuxa.keys >> /home/admin/.ssh/authorized_keys"
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
