# See https://zellwk.com/blog/github-actions-deploy/ an explanation of this code
name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with scp
        run: ssh admin@us.sys2nix.de git clone https://github.com/mrtuxa/nightgod.agency.git /tmp/nigtgod.agency
      - name: deploy to nginx
        run: ssh admin@us.sys2nix.de sudo mv /tmp/nightgod.agency/ /var/www/html/nightgod.agency/
